import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
const code=await readFile(new URL('../google-apps-script/Code.gs',import.meta.url),'utf8');
function receiver(props={SITE_ORIGIN:'https://duckxyz06.github.io',SPREADSHEET_ID:'test-sheet'}){
 const rows=[];const formats=[];let locked=false;
 const sheet={getLastRow:()=>rows.length,appendRow:r=>rows.push(r),setFrozenRows(){},getRange:(row,col,rowCount,columnCount)=>({setFontFamily(value){formats.push({row,col,rowCount,columnCount,font:value});return this},setFontSize(value){formats.at(-1).size=value;return this},setHorizontalAlignment(value){formats.at(-1).horizontal=value;return this},setVerticalAlignment(value){formats.at(-1).vertical=value;return this},setBorder(...values){formats.at(-1).borders=values;return this},setValue:value=>{rows[row-1][col-1]=value},createTextFinder:id=>({matchEntireCell:()=>({findNext:()=>rows.some(r=>r[1]===id)?{}:null})})})};
 const context=vm.createContext({PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet,insertSheet:()=>sheet}),flush(){}},LockService:{getScriptLock:()=>({waitLock:()=>{locked=true},releaseLock:()=>{locked=false}})},HtmlService:{XFrameOptionsMode:{ALLOWALL:1},createHtmlOutput:html=>({html,setXFrameOptionsMode(){return this}})},console:{error(){}},ContentService:{createTextOutput:()=>({setMimeType(){}}),MimeType:{JSON:1}}});vm.runInContext(code,context);
 return {rows,formats,format:()=>context.formatWishesSheet(),send:p=>{const out=context.doPost({parameter:{...p}});const match=out.html.match(/window.top.postMessage\((.*),"https:/);return {result:JSON.parse(match[1]),html:out.html,locked}}};
}
const valid={id:'12345678-1234-1234-1234-123456789012',sender:'An',message:'Chúc Đức nhiều niềm vui!',photoId:'photos/test.jpg',photoTitle:'Ngày đẹp trời'};
test('saves all fields and acknowledges only after append; retries are idempotent',()=>{const r=receiver();assert.equal(r.send({...valid,answer:'Bình an',question:'Bạn thích điều gì?'}).result.ok,true);assert.equal(r.rows.length,2);assert.equal(r.rows[1][2],'An');assert.equal(r.rows[1][5],valid.message);assert.equal(r.rows[1][7],'Bình an');assert.equal(r.rows[1][8],'Bạn thích điều gì?');assert.equal(r.send(valid).result.ok,true);assert.equal(r.rows.length,2);});
test('rejects empty and overlong submissions without writing rows',()=>{const r=receiver();assert.equal(r.send({...valid,sender:'  '}).result.ok,false);assert.equal(r.send({...valid,message:'x'.repeat(2001)}).result.ok,false);assert.equal(r.rows.length,0);});
test('neutralizes spreadsheet formulas and escapes script terminators in response',()=>{const r=receiver();assert.equal(r.send({...valid,sender:'=HYPERLINK("x")',message:'</script><script>alert(1)</script>'}).result.ok,true);assert.equal(r.rows[1][2],"'=HYPERLINK(\"x\")");assert.equal(r.rows[1][5],'</script><script>alert(1)</script>');const out=r.send({...valid,id:'bad</script>'});assert.equal(out.html.includes('bad</script>'),false);});
test('fails safely when not configured; rejects honeypot',()=>{const r=receiver({});assert.equal(r.send(valid).result.ok,false);assert.equal(r.rows.length,0);const configured=receiver();assert.equal(configured.send({...valid,website:'bot'}).result.ok,false);assert.equal(configured.rows.length,0);});
test('email is optional, saved separately, and malformed email never writes a wish',()=>{const r=receiver();assert.equal(r.send({...valid,email:'duc@example.com'}).result.ok,true);assert.equal(r.rows[0][9],'Email (không bắt buộc)');assert.equal(r.rows[1][9],'duc@example.com');const invalid=receiver();assert.equal(invalid.send({...valid,email:'not-an-email'}).result.ok,false);assert.equal(invalid.rows.length,0);const optional=receiver();assert.equal(optional.send(valid).result.ok,true);assert.equal(optional.rows[1][9],'');});

test('wish table uses requested font, size, alignment and full borders',()=>{const r=receiver();assert.equal(r.send(valid).result.ok,true);assert.deepEqual(r.formats.at(-1),{row:1,col:1,rowCount:2,columnCount:10,font:'Times New Roman',size:14,horizontal:'center',vertical:'middle',borders:[true,true,true,true,true,true]});r.format();assert.equal(r.rows.length,2);assert.deepEqual(r.formats.at(-1),r.formats[0]);});
