import './style.css';
import {createCastle} from './scene';
import {applyLanguage,language,t,photoTitle} from './language';
import {createMusic} from './music';
const $=s=>document.querySelector(s);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const scene=createCastle($('#scene'),reduced);
let config={ownerName:'Nguyễn Việt Đức',appsScriptUrl:'',question:'Nếu gửi mình một điều ước, bạn sẽ ước điều gì?'},selected=null,request=null,album=[],albumLoaded=false;
const music=createMusic();
async function load(){try{const [c,p]=await Promise.all([fetch('./config.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('config');return r.json()}),fetch('./photos.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('photos');return r.json()})]);config={...config,...c};$('#owner').textContent=config.ownerName;album=p;albumLoaded=true;render(p);scene.setPhotos(p,openLetter);refreshLanguage();loadReport();}catch{$('#count').textContent=t('loadError');$('#empty').hidden=false;$('#album-note').hidden=false;$('#album-note').textContent=t('albumError');}}load();
function render(photos){$('#count').textContent=`${String(photos.length).padStart(2,'0')} ${t('count')}`;$('#empty').hidden=photos.length>0;photos.forEach((p,i)=>{const button=document.createElement('button');button.className='photo-card';button.setAttribute('aria-label',language()==='en'?`View ${photoTitle(p)} and write a wish`:`Xem ${photoTitle(p)} và viết lời chúc`);const frame=document.createElement('div');frame.className='photo-frame';const img=document.createElement('img');img.src=p.thumbnail||p.src;img.alt=photoTitle(p);img.loading='lazy';img.decoding='async';img.onerror=()=>{img.hidden=true;frame.textContent=t('imageError');};frame.append(img);const meta=document.createElement('div');meta.className='photo-meta';const name=document.createElement('div');name.textContent=photoTitle(p);const num=document.createElement('span');num.textContent=String(i+1).padStart(2,'0');meta.append(name,num);button.append(frame,meta);button.addEventListener('click',()=>openLetter(p));$('#photos').append(button);});}
function openLetter(p=null){selected=p;$('#photo-title').textContent=p?photoTitle(p):t('general');$('#letter-photo').hidden=!p;$('#letter-symbol').hidden=!!p;if(p){$('#letter-photo').src=p.src;$('#letter-photo').alt=p.title;}$('#form-status').textContent=config.appsScriptUrl?'':t('draft');try{const draft=JSON.parse(localStorage.getItem('vietduc-wish-draft')||'{}');for(const name of ['sender','message','answer','question'])if(!$('#wish-form').elements[name].value)$('#wish-form').elements[name].value=draft[name]||'';}catch{}$('#letter').showModal();$('#sender').focus();}
for(const id of ['open-letter','bottom-letter','empty-letter'])$('#'+id).addEventListener('click',()=>openLetter());$('#close-letter').onclick=()=>$('#letter').close();$('#letter').addEventListener('click',e=>{if(e.target===$('#letter')){const r=$('#letter').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#letter').close();}});
let paused=reduced;function updateMotion(){document.body.classList.toggle('motion-paused',paused);scene.setPaused(paused);$('#motion').textContent=paused?'▷':'Ⅱ';$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').setAttribute('aria-label',paused?t('resume'):t('pause'));}updateMotion();$('#motion').onclick=()=>{paused=!paused;updateMotion()};$('#tour').onclick=()=>{scene.tour();paused=false;document.body.classList.remove('motion-paused');$('#motion').textContent='Ⅱ';$('#motion').setAttribute('aria-pressed','false');$('#motion').setAttribute('aria-label',t('pause'));};
for(const [id,orbit]of [['grid-view',false],['orbit-view',true]])$('#'+id).onclick=()=>{$('#photos').classList.toggle('orbit-mode',orbit);for(const x of ['grid-view','orbit-view']){$('#'+x).classList.toggle('active',x===id);$('#'+x).setAttribute('aria-pressed',String(x===id));}};
function getDraft(){return Object.fromEntries(['sender','message','answer','question'].map(k=>[k,$('#wish-form').elements[k].value]));}$('#wish-form').addEventListener('input',()=>{try{localStorage.setItem('vietduc-wish-draft',JSON.stringify(getDraft()))}catch{}});
const trustedOrigin=o=>/^https:\/\/(?:script|[a-z0-9-]+-script)\.googleusercontent\.com$/.test(o)||o==='https://script.google.com';
window.addEventListener('message',e=>{if(!request||!trustedOrigin(e.origin)||e.data?.type!=='vietduc-wish-result'||e.data.id!==request.id)return;finish(e.data.ok,e.data.message);});
function finish(ok,message){if(!request)return;clearTimeout(request.timer);request.frame.remove();request.form.remove();request=null;$('#send').disabled=false;$('#send').innerHTML=`${t('send')} <span>↗</span>`;$('#form-status').textContent=ok?t('received'):message||t('failed');if(ok){$('#wish-form').reset();try{localStorage.removeItem('vietduc-wish-draft');localStorage.removeItem('vietduc-pending-id')}catch{}}}
$('#wish-form').addEventListener('submit',e=>{e.preventDefault();if(request)return;const data=getDraft();if(!data.sender.trim()||!data.message.trim()){$('#form-status').textContent=t('required');return;}if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(config.appsScriptUrl)){$('#form-status').textContent=t('unconnected');return;}let id;try{id=localStorage.getItem('vietduc-pending-id');const previous=JSON.parse(localStorage.getItem('vietduc-pending-data')||'null');if(!id||JSON.stringify(previous)!==JSON.stringify({...data,photoId:selected?.id||''})){id=crypto.randomUUID();localStorage.setItem('vietduc-pending-id',id);localStorage.setItem('vietduc-pending-data',JSON.stringify({...data,photoId:selected?.id||''}));}}catch{id=crypto.randomUUID()}
 const iframe=document.createElement('iframe');iframe.hidden=true;iframe.name=`wish-${id}`;iframe.title='Kết nối hộp thư';document.body.append(iframe);const form=document.createElement('form');form.hidden=true;form.method='POST';form.action=config.appsScriptUrl;form.target=iframe.name;for(const [name,value] of Object.entries({...data,id,photoId:selected?.id||'',photoTitle:selected?.title||'Lời chúc chung',prompt:questionText(),website:$('#wish-form').elements.website.value})){const input=document.createElement('input');input.name=name;input.value=value;form.append(input);}document.body.append(form);request={id,frame:iframe,form,timer:setTimeout(()=>finish(false,t('timeout')),25000)};$('#send').disabled=true;$('#send').textContent=t('sending');$('#form-status').textContent=t('transferring');form.submit();});

async function loadReport(){try{const r=await fetch('./photo-report.json',{cache:'no-store'});if(!r.ok)return;const report=await r.json();if(!report.failed?.length)return;const details=document.createElement('details');details.className='photo-report';const summary=document.createElement('summary');summary.textContent=`${report.failed.length} ${t('report')}`;const list=document.createElement('ul');for(const item of report.failed){const li=document.createElement('li');li.textContent=`${item.file}: ${item.message}`;list.append(li);}details.append(summary,list);$('#photos').before(details);}catch{}}

function questionText(){return language()==='en'?(config.questionEnglish||(config.question==='Nếu gửi mình một điều ước, bạn sẽ ước điều gì?'?t('question'):config.question)):config.question;}
function updateMusic(){const on=music.playing;$('#music').setAttribute('aria-pressed',String(on));$('#music').setAttribute('aria-label',t(on?'musicOff':'musicOn'));$('#music').innerHTML=`${on?'♫':'♪'} <span>${language()==='en'?'Music':'Nhạc'}</span>`;$('#music').title=t(on?'musicOff':'musicOn');}
function refreshLanguage(){applyLanguage(language());$('#count').textContent=albumLoaded?`${String(album.length).padStart(2,'0')} ${t('count')}`:t('loading');$('#question-label').textContent=questionText();for(const [i,card]of [...$('#photos').children].entries()){const p=album[i];if(!p)continue;card.setAttribute('aria-label',language()==='en'?`View ${photoTitle(p)} and write a wish`:`Xem ${photoTitle(p)} và viết lời chúc`);card.querySelector('.photo-meta>div').textContent=photoTitle(p);const img=card.querySelector('img');if(img)img.alt=photoTitle(p);}
$('#photo-title').textContent=selected?photoTitle(selected):t('general');if(selected)$('#letter-photo').alt=photoTitle(selected);$('#send').innerHTML=request?t('sending'):`${t('send')} <span>↗</span>`;if(!request&&!config.appsScriptUrl&&$('#letter').open)$('#form-status').textContent=t('draft');updateMotion();updateMusic();}
$('#language').addEventListener('change',e=>{applyLanguage(e.target.value);refreshLanguage()});
$('#music').addEventListener('click',async()=>{try{await music.toggle();updateMusic()}catch{$('#music').title=t('musicError')}});
document.addEventListener('visibilitychange',()=>{(document.hidden?music.hide():music.show()).catch(()=>{})});
refreshLanguage();
