import './style.css';
import {createCastle} from './scene';
const $=s=>document.querySelector(s);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const scene=createCastle($('#scene'),reduced);
let config={ownerName:'Nguyễn Việt Đức',appsScriptUrl:'',question:'Nếu gửi mình một điều ước, bạn sẽ ước điều gì?'},selected=null,request=null;
async function load(){try{const [c,p]=await Promise.all([fetch('./config.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('config');return r.json()}),fetch('./photos.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('photos');return r.json()})]);config={...config,...c};$('#owner').textContent=config.ownerName;$('#question-label').textContent=config.question;render(p);scene.setPhotos(p,openLetter);loadReport();}catch{$('#count').textContent='Chưa tải được album';$('#empty').hidden=false;$('#album-note').hidden=false;$('#album-note').textContent='Album tạm thời chưa tải được. Vui lòng tải lại trang sau ít phút.';}}load();
function render(photos){$('#count').textContent=`${String(photos.length).padStart(2,'0')} khoảnh khắc được lưu giữ`;$('#empty').hidden=photos.length>0;photos.forEach((p,i)=>{const button=document.createElement('button');button.className='photo-card';button.setAttribute('aria-label',`Xem ${p.title} và viết lời chúc`);const frame=document.createElement('div');frame.className='photo-frame';const img=document.createElement('img');img.src=p.thumbnail||p.src;img.alt=p.title;img.loading='lazy';img.decoding='async';img.onerror=()=>{img.hidden=true;frame.textContent='Ảnh tạm thời không tải được';};frame.append(img);const meta=document.createElement('div');meta.className='photo-meta';const name=document.createElement('div');name.textContent=p.title;const num=document.createElement('span');num.textContent=String(i+1).padStart(2,'0');meta.append(name,num);button.append(frame,meta);button.addEventListener('click',()=>openLetter(p));$('#photos').append(button);});}
function openLetter(p=null){selected=p;$('#photo-title').textContent=p?.title||'Gửi đến lâu đài của Đức';$('#letter-photo').hidden=!p;$('#letter-symbol').hidden=!!p;if(p){$('#letter-photo').src=p.src;$('#letter-photo').alt=p.title;}$('#form-status').textContent=config.appsScriptUrl?'':'Hộp thư chưa được kết nối. Bạn có thể viết trước; bản nháp được giữ trong trình duyệt này.';try{const draft=JSON.parse(localStorage.getItem('vietduc-wish-draft')||'{}');for(const name of ['sender','message','answer','question'])if(!$('#wish-form').elements[name].value)$('#wish-form').elements[name].value=draft[name]||'';}catch{}$('#letter').showModal();$('#sender').focus();}
for(const id of ['open-letter','bottom-letter','empty-letter'])$('#'+id).addEventListener('click',()=>openLetter());$('#close-letter').onclick=()=>$('#letter').close();$('#letter').addEventListener('click',e=>{if(e.target===$('#letter')){const r=$('#letter').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#letter').close();}});
let paused=reduced;function updateMotion(){document.body.classList.toggle('motion-paused',paused);scene.setPaused(paused);$('#motion').textContent=paused?'▷':'Ⅱ';$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').setAttribute('aria-label',paused?'Bật chuyển động':'Tạm dừng chuyển động');}updateMotion();$('#motion').onclick=()=>{paused=!paused;updateMotion()};$('#tour').onclick=()=>{scene.tour();paused=false;document.body.classList.remove('motion-paused');$('#motion').textContent='Ⅱ';$('#motion').setAttribute('aria-pressed','false');$('#motion').setAttribute('aria-label','Tạm dừng chuyển động');};
for(const [id,orbit]of [['grid-view',false],['orbit-view',true]])$('#'+id).onclick=()=>{$('#photos').classList.toggle('orbit-mode',orbit);for(const x of ['grid-view','orbit-view']){$('#'+x).classList.toggle('active',x===id);$('#'+x).setAttribute('aria-pressed',String(x===id));}};
function getDraft(){return Object.fromEntries(['sender','message','answer','question'].map(k=>[k,$('#wish-form').elements[k].value]));}$('#wish-form').addEventListener('input',()=>{try{localStorage.setItem('vietduc-wish-draft',JSON.stringify(getDraft()))}catch{}});
const trustedOrigin=o=>/^https:\/\/(?:script|[a-z0-9-]+-script)\.googleusercontent\.com$/.test(o)||o==='https://script.google.com';
window.addEventListener('message',e=>{if(!request||!trustedOrigin(e.origin)||e.data?.type!=='vietduc-wish-result'||e.data.id!==request.id)return;finish(e.data.ok,e.data.message);});
function finish(ok,message){if(!request)return;clearTimeout(request.timer);request.frame.remove();request.form.remove();request=null;$('#send').disabled=false;$('#send').innerHTML='Gửi lời nhắn <span>↗</span>';$('#form-status').textContent=ok?'Đã nhận được lời nhắn của bạn. Cảm ơn bạn đã để lại một vì sao!':message||'Chưa gửi được. Bản nháp vẫn được giữ, bạn có thể thử lại.';if(ok){$('#wish-form').reset();try{localStorage.removeItem('vietduc-wish-draft');localStorage.removeItem('vietduc-pending-id')}catch{}}}
$('#wish-form').addEventListener('submit',e=>{e.preventDefault();if(request)return;const data=getDraft();if(!data.sender.trim()||!data.message.trim()){$('#form-status').textContent='Vui lòng nhập tên và lời chúc.';return;}if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(config.appsScriptUrl)){$('#form-status').textContent='Hộp thư chưa được kết nối với Google Sheets. Lời nhắn chưa được gửi; bản nháp đã lưu trên thiết bị này.';return;}let id;try{id=localStorage.getItem('vietduc-pending-id');const previous=JSON.parse(localStorage.getItem('vietduc-pending-data')||'null');if(!id||JSON.stringify(previous)!==JSON.stringify({...data,photoId:selected?.id||''})){id=crypto.randomUUID();localStorage.setItem('vietduc-pending-id',id);localStorage.setItem('vietduc-pending-data',JSON.stringify({...data,photoId:selected?.id||''}));}}catch{id=crypto.randomUUID()}
 const iframe=document.createElement('iframe');iframe.hidden=true;iframe.name=`wish-${id}`;iframe.title='Kết nối hộp thư';document.body.append(iframe);const form=document.createElement('form');form.hidden=true;form.method='POST';form.action=config.appsScriptUrl;form.target=iframe.name;for(const [name,value] of Object.entries({...data,id,photoId:selected?.id||'',photoTitle:selected?.title||'Lời chúc chung',prompt:config.question,website:$('#wish-form').elements.website.value})){const input=document.createElement('input');input.name=name;input.value=value;form.append(input);}document.body.append(form);request={id,frame:iframe,form,timer:setTimeout(()=>finish(false,'Chưa nhận được xác nhận. Bạn có thể thử lại; hệ thống giữ mã gửi để tránh ghi trùng.'),25000)};$('#send').disabled=true;$('#send').textContent='Đang gửi…';$('#form-status').textContent='Đang chuyển lời nhắn đến Đức…';form.submit();});

async function loadReport(){try{const r=await fetch('./photo-report.json',{cache:'no-store'});if(!r.ok)return;const report=await r.json();if(!report.failed?.length)return;const details=document.createElement('details');details.className='photo-report';const summary=document.createElement('summary');summary.textContent=`${report.failed.length} ảnh chưa mở được · Xem chi tiết`;const list=document.createElement('ul');for(const item of report.failed){const li=document.createElement('li');li.textContent=`${item.file}: ${item.message}`;list.append(li);}details.append(summary,list);$('#photos').before(details);}catch{}}
